version: '3'
services:
  db:
    image: "postgres:9.4"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
      context: .
      dockerfile: ./Dockerfile.postgresql
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data